name: Selenium E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000 || exit 1
      env:
        NODE_ENV: production
        
    - name: Run Selenium tests
      run: |
        npm run test:selenium
      env:
        HEADLESS: true
        BROWSER: ${{ matrix.browser }}
        BASE_URL: http://localhost:3000
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-test-results-${{ matrix.browser }}
        path: |
          test-results/
          screenshots/
        retention-days: 7
        
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: selenium-failure-reports-${{ matrix.browser }}
        path: |
          test-results/
          screenshots/
        retention-days: 30

  selenium-tests-mobile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000 || exit 1
      env:
        NODE_ENV: production
        
    - name: Run mobile Selenium tests
      run: |
        npm run test:selenium:home
      env:
        HEADLESS: true
        BROWSER: chrome
        BASE_URL: http://localhost:3000
        MOBILE: true
        
    - name: Upload mobile test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-mobile-test-results
        path: |
          test-results/
          screenshots/
        retention-days: 7

  performance-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Start application
      run: |
        npm start &
        sleep 10
        curl -f http://localhost:3000 || exit 1
      env:
        NODE_ENV: production
        
    - name: Run performance tests
      run: |
        npm run test:selenium:home
      env:
        HEADLESS: true
        BROWSER: chrome
        BASE_URL: http://localhost:3000
        PERFORMANCE_TEST: true
        
    - name: Upload performance test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-performance-results
        path: |
          test-results/
          screenshots/
        retention-days: 7
